### PR TITLE
HOSTAPD plugin

### PR DESCRIPTION
**Pull request by acsaba1977**
Enable HOSTAPD by default in order to allow Raspberry PI zero get accessible via WIFI. Will allow user to access Raspberry PI using WIFI and SSH connection without using keyboard and monitor.

### CODE REVIEW

**Comment by acsaba1977** [comment]
In case you consider that my proposal is ok with you, please add it to the master branch. I did several tests using PI zero with wifi and PI 3.

**Comment by TheSin-** [comment]
Can you move it to disabled and I'll include it for sure.  Just don't want it on by default specially using the 192.168.x.x network as that would cause me tons of grief.

**Comment by acsaba1977** [comment]
I will put in disabled. Regarding network address, from my standpoint,  anything else would be ok. 192.168.x.x is just a proposal. 10.x.x.x or 172.16.x.x are good as well.

**Comment by TheSin-** [comment]
192.168.x.x is perfectly fine, though I think industry standard for it would have been on the 10.x.x.x network.  That being said this is a great addition thank you very much for it!

**Comment by acsaba1977** [comment]
You’re welcome! And thank you, too.

**Pull request merged**
